# Generated by Django 6.0.1 on 2026-05-02 05:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='SOB, SOPAM, FOL, FSS, FST, IDS', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'faculties',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_faculties_name')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('vc', 'Vice Chancellor'), ('director', 'Director'), ('hod', 'Head of Department'), ('technician', 'Technician')], default='student', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voice.faculty')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('suggestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('welfare', 'Welfare'), ('gender', 'Gender Issue'), ('academic', 'Academic'), ('technical', 'Technical'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('visibility', models.CharField(choices=[('confidential', 'Confidential'), ('open', 'Open')], max_length=15)),
                ('attachment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('forwarded', 'Forwarded'), ('resolved', 'Resolved')], default='pending', max_length=15)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_suggestions', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voice.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('comm_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='voice.suggestion')),
            ],
            options={
                'db_table': 'communications',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionChain',
            fields=[
                ('chain_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('forwarded', 'Forwarded'), ('resolved', 'Resolved')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_from', to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_entries', to='voice.suggestion')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suggestion_chain',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='idx_users_username'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_users_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['faculty'], name='idx_users_faculty'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['student'], name='idx_suggestions_student'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['status'], name='idx_suggestions_status'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['current_handler'], name='idx_suggestions_handler'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['visibility'], name='idx_suggestions_visibility'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['faculty'], name='idx_suggestions_faculty'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['created_at'], name='idx_suggestions_created'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['suggestion'], name='idx_comm_suggestion'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['user'], name='idx_comm_user'),
        ),
        migrations.AddIndex(
            model_name='suggestionchain',
            index=models.Index(fields=['suggestion'], name='idx_chain_suggestion'),
        ),
        migrations.AddIndex(
            model_name='suggestionchain',
            index=models.Index(fields=['from_user'], name='idx_chain_from_user'),
        ),
        migrations.AddIndex(
            model_name='suggestionchain',
            index=models.Index(fields=['to_user'], name='idx_chain_to_user'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user'], name='idx_sessions_user'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['token'], name='idx_sessions_token'),
        ),
    ]
