# Generated by Django 6.0.1 on 2026-05-02 14:08

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voice.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
            ],
            options={
                'verbose_name': 'Head of Department',
                'verbose_name_plural': 'Heads of Department',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voice.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voice.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ViceChancellor',
            fields=[
            ],
            options={
                'verbose_name': 'Vice Chancellor',
                'verbose_name_plural': 'Vice Chancellors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voice.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
