# Generated by Django 6.0.1 on 2026-05-03 10:02

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_director_hod_student_vicechancellor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Room number (e.g., A101)', max_length=10, unique=True)),
                ('type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('dormitory', 'Dormitory')], default='single', max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accommodation_rooms',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationDirector',
            fields=[
            ],
            options={
                'verbose_name': 'Director of Accommodation',
                'verbose_name_plural': 'Directors of Accommodation',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voice.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='category',
            field=models.CharField(choices=[('welfare', 'Welfare'), ('gender', 'Gender Issue'), ('academic', 'Academic'), ('technical', 'Technical'), ('other', 'Other'), ('accommodation', 'Accommodation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('vc', 'Vice Chancellor'), ('director', 'Director'), ('hod', 'Head of Department'), ('technician', 'Technician'), ('accommodation_director', 'Director of Accommodation')], default='student', max_length=30),
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_requests', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='voice.room')),
            ],
            options={
                'db_table': 'accommodation_maintenance_requests',
                'ordering': ['-reported_date'],
                'indexes': [models.Index(fields=['room'], name='idx_maint_room'), models.Index(fields=['status'], name='idx_maint_status')],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='voice.room')),
            ],
            options={
                'db_table': 'accommodation_allocations',
                'ordering': ['-allocation_date'],
                'indexes': [models.Index(fields=['student'], name='idx_alloc_student'), models.Index(fields=['room'], name='idx_alloc_room'), models.Index(fields=['status'], name='idx_alloc_status')],
            },
        ),
    ]
