# Generated by Django 6.0.1 on 2026-05-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_room_accommodationdirector_alter_suggestion_category_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='allocation',
            name='idx_alloc_student',
        ),
        migrations.RemoveIndex(
            model_name='allocation',
            name='idx_alloc_room',
        ),
        migrations.RemoveIndex(
            model_name='allocation',
            name='idx_alloc_status',
        ),
        migrations.RemoveIndex(
            model_name='maintenancerequest',
            name='idx_maint_room',
        ),
        migrations.RemoveIndex(
            model_name='maintenancerequest',
            name='idx_maint_status',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='room',
        ),
        migrations.DeleteModel(
            name='Allocation',
        ),
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
