# Generated by Django 6.0.1 on 2026-05-04 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0004_remove_allocation_idx_alloc_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. Letters, digits, slash (/), dot (.), underscore (_), and hyphen (-) only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Username can only contain letters, digits, slash (/), dot (.), underscore (_), and hyphen (-).', regex='^[\\w./-]+$')]),
        ),
    ]
